In [4]:
import numpy
n = numpy.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [5]:
type(n)

numpy.ndarray

In [8]:
#two dimensional array
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
#three dimensional array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
m =numpy.asarray([[123,12,123,33,42],[],[]])
m

array([list([123, 12, 123, 33, 42]), list([]), list([])], dtype=object)

In [16]:
import cv2
im_gray = cv2.imread("smallgray.png",0)
im_gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [17]:
import cv2
im_bgr = cv2.imread("smallgray.png",1)
im_bgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [18]:
cv2.imwrite("newsmallgray.png",im_gray)

True

In [20]:
im_gray[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)